### ISSUE TITLE
A different mqtt_node may be needed

### ISSUE THREAD

**Issue by foolip** [ThermIQ/thermiq_mqtt-ha#11]
## Version of the custom_component

I installed v1.2.2. Note that there is no const.py other than custom_components/hacs/const.py.

## Configuration

```yaml
thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-mqtt-bb
```

## Describe the bug

The configuration in https://github.com/ThermIQ/thermiq_mqtt-ha#component-configuration didn't work for me. It says that `mqtt_node` should be "ThermIQ/ThermIQ-mqtt", but that doesn't work. By looking for what messages are being published, I could figure out that it should be "ThermIQ/ThermIQ-mqtt-bb"

It would be great if the docs mentioned that the MQTT topic might vary, and how to figure out which one to use.

**Comment by ThermIQ** [comment]
The node name is freely configurable in ThermIQ-MQTT WiFi Config. I'll extend the mention off that in configuration_thermiq.yaml
