### ISSUE TITLE
Include breaking changes in release notes

### ISSUE THREAD

**Issue by lightheaded** [ThermIQ/thermiq_mqtt-ha#22]
Hi!

I've been enjoying the work you're doing on this repository. It is reat one of the most useful integrations on my home. I am super happy about the recent pace of development and ways you keep improving the integration and implementing feature requests and suggestions by rhe community. Hats off to that! 

That being said, I've had at least three separate occasions where I've been left with broken dashboards and integrations/automations not working after an update of the component. I'm a developer myself, and I understand the need for breaking changes, especially for such and early-stage project. To make updates less dreaded, I would suggest two things:

1. Adopt semantic versioning (https://semver.org/), where  major versions denote breaking changes (such as the recent addition of domains to all sensors or the change which translated sensor names to English). This would make it obvious, that if I upgrade, I need to put some effort into fixing my numerous dashboards and integrations and I'll need to set aside some time for that.
2. And/or include upgrade instructions in the readme. Such as the recent additions for debug flags or language configurations that need to be added to the config if desired. I understand this was likely a bug that on two separate occasions caused the integration to completely stop working if the configuration entried were not added, as thebcode expected them to be defined and didn't have a null-check for that. But still it would be nice to be introduced into what's new or especially what could break right on the home assistant component upgrade window.

Thanks for all the hard work you're doing 💪

**Comment by lightheaded** [comment]
And perhaps one more thought – with all the improvements some stuff becomes obsolete, like some of the automations. It would be helpful to know which automations, helpers, assets etc. can be deleted after upgrading. I still have some helpers and automations lying around that I'm not sure are needed. Some seem to be left over, some might be introduced by the integration itself?

**Comment by ThermIQ** [comment]
Thanks for the feedback, yes it's been many breaking changes sofar and I understand it's hard to keep track. I'm new to HA and HACS and learning how to get the update message through to HACS. The github page have stayed acurate with the latest release but it's not necessarily where you go every time you upgrade.

There are currently no automations or services needed for ThermIQ, everything is integrated and only configuration.yaml needs to be updated when setting it up. This is described the README

I believe most of my intended features are now in place and that development pace will slow down and focus on any remaining bugs.

Next breaking step will be to allow the integration to handle multiple heatpumps. Instructions will be visible when updating in HACS

**Comment by lightheaded** [comment]
Thanks a lot for the feedback and the explanation 😊
