### ISSUE TITLE
Likely typo in language register mapping

### ISSUE THREAD

**Issue by foolip** [ThermIQ/thermiq_mqtt-ha#24]
Here:

https://github.com/ThermIQ/thermiq_mqtt-ha/blob/6bda6ee1f2b0d1ff5b44a8cc7cf1010c90fe8f7a/custom_components/thermiq_mqtt/thermiq_regs.py#L107

That 'sensor_spr㤫' should probably be 'sensor_språk' or 'sensor_lang'. I haven't checked how the value is used.

**Comment by ThermIQ** [comment]
A funny mix of english names and swedish units... Will fix that in the backend generation of things. 

The unit dictionary seems to be superfluous as well since the units are included in the reg_id dictionary.

**Comment by foolip** [comment]
> A funny mix of english names and swedish units... Will fix that in the backend generation of things.

Ah, so is this list generated from some other source?

> The unit dictionary seems to be superfluous as well since the units are included in the reg_id dictionary.

I was thinking about that too in the context of 'legionella_runtime_m'. The unit there is 'dygn' and it actually never shows up because 'sensor_dygn_input' isn't mapped, but if it were mapped I don't see where the unit is translated.

**Comment by ThermIQ** [comment]
I generate it all from the same database as I have for ThermIQ2-WEB to make it consistent. 

There seems to be a couple of hickups in the database extraction when making the HA component multilingual that I will look into

**Comment by ThermIQ** [comment]
Fixed in v1.3.1

**Comment by foolip** [comment]
Thanks! Unfortunately, it looks like the release wasn't tagged so I can't upgrade in HACS.

**Comment by ThermIQ** [comment]
It's labeled as beta release and you need to allow that in the HACS pop-up

**Comment by foolip** [comment]
This is what I see when checking that checkbox:
![image](https://user-images.githubusercontent.com/498917/149659254-80ea3105-5815-4b08-91b0-9189c78204f7.png)

I guess it's somehow related to the rename in the manifest that happened recently.

**Comment by ThermIQ** [comment]
Yes, I had to change the directory name to thermiq_mqtt in order to be compliant with HACS test. 

Not sure what I did to resolve it in HACS but I did have the same message and it did go away somehow :-)

Does a manual "update information" or "redownload" of the component resolve it? I don't think a full re-install is needed.

**Comment by ThermIQ** [comment]
Can you see v1.3.1 in the list?

**Comment by foolip** [comment]
I don't remember if it was in the list when I took the screenshot (on my phone). Just now, on the laptop, I removed it entirely (confirmed that  and tried to install fresh with v1.3.1 directly. First I see this:
![image](https://user-images.githubusercontent.com/498917/149659657-ed5f4972-caf7-4b2d-80c0-31e214a1f94f.png)

Then, when clicking download, this flashes by:
![image](https://user-images.githubusercontent.com/498917/149659691-eabf4ee8-1c47-40f3-85eb-cf5d39e6e419.png)

I had to try a few times before I catch it with a screenshot.

This is almost certainly related to https://github.com/ThermIQ/thermiq_mqtt-ha/commit/1cd1edeba9dc608c4c1ec01b00522da9a51cab42, there's something somewhere that expects the domain and directory to match, and has the old domain "thermiq" still.

**Comment by foolip** [comment]
OK, I've tried forking the repo and installing it as a custom repository. That works. So I'm pretty sure the problem isn't in the state of the code, but perhaps in how this integration is registered with HACS. Maybe the name "thermiq" appears somewhere in there?

**Comment by ThermIQ** [comment]
I now have a fresh install of HA and I do not see it any longer.

Where you able to install the new version, then this is warning or was it an Error?
