### ISSUE TITLE
Some start_interval_min_m translations are wrong

### ISSUE THREAD

**Issue by foolip** [ThermIQ/thermiq_mqtt-ha#28]
Here:

https://github.com/ThermIQ/thermiq_mqtt-ha/blob/46367afd713a8a7d436b8a057d0eb44460fd1b5c/custom_components/thermiq_mqtt/thermiq_regs.py#L234

I think 'Minimum idle interval' and 'Minimum vilointervall' are wrong. Based on the behavior I see with time_to_start_min_m right after the compressor starts, this register is the minimum time between starts, it's not the time to stay idle in between "runs".

I would suggest 'Minimum start interval' and 'Minimum startintervall'.

**Comment by ThermIQ** [comment]
Will be changed according to your suggestion in a comming release
