### ISSUE TITLE
Exception in message_received hass.states.async_set(DOMAIN+".time_str", json_dict[“time”]) KeyError: ‘time’

### ISSUE THREAD

**Issue by klausdm** [ThermIQ/thermiq_mqtt-ha#30]
`* Exception in message_received when handling msg on ‘danfossvp/danfossvp-mqtt/data’: “i deleted stuff here”…,“Time”: “2022-03-05 21:18:39 CET”,“timestamp”: 1646511519 }’ Traceback (most recent call last): File “/config/custom_components/thermiq_mqtt/init.py”, line 366, in message_received hass.states.async_set(DOMAIN+".time_str", json_dict[“time”]) KeyError: ‘time’`

- I fixed it locally on my setup by changing “time” to “Time” in line 366 init.py - it can now parse the data successfully.
- Note that i have a ThermIQ with firmware 1.4

**Comment by ThermIQ** [comment]
Fixed in v1.3.5
