### ISSUE TITLE
Error in language selector

### ISSUE THREAD

**Issue by ioT-enthusiast** [ThermIQ/thermiq_mqtt-ha#35]
There is an error in __init__.py Line 92
AVAILABLE_LANGUAGES = ['en','sw','fi','no','en','de','se']

This list (and the index up to 7) is inconsitent with the language registers in thermiq_regs.py line 151 ff.
  'outdoor_t'                    : ['Outdoor temp.', 'Utomhustemp.', 'Ulkolämpötila', 'Utendørstemp.', 'Außentemperatur'],

Also it es inconsistent with the documentation of the Yaml config.
language: 'en'   # Change friendly names of values. Implemented languages: en,se,fi,no,de

Due to this error, if e.g. 'de' is configured, the integration cannot be set up during starting of HA.

Changing __init__.py Line 92 to
AVAILABLE_LANGUAGES = ['en','se','fi','no','de']
works correctly with 'de' configuration and seems to meet the index of the translations.

**Comment by ThermIQ** [comment]
corrected in v1.3.6
