### ISSUE TITLE
Hot water production sensor

### ISSUE THREAD

**Issue by markora** [ThermIQ/thermiq_mqtt-ha#40]
binary_sensor.thermiq_mqtt_hotwaterproduction_on is constantly in state "on".

It does not seem to change after updating to 1.3.9 version. Was working correctly with previous 1.3.5 version.

Anybody else having same issue?

**Comment by Dauzzen** [comment]
![image](https://user-images.githubusercontent.com/98492697/201060327-559c6a06-6d33-4adf-b2b8-ad9ef545af47.png)

I have the same problem. 
There are also some other sensors that are constantly on. Some of them shouldent be.

**'binary_sensor.thermiq_mqtt_opt_hgw_installed'**
I have a Diplomat Duo Optimum 12 and as far as I know it hasn’t got HGW. The “G2” version has.

**'binary_sensor.thermiq_mqtt_opt_optimum_installed'**
This seems to be right.

**'binary_sensor.thermiq_mqtt_opt_flowguard_installed'**
I don’t know if I have “Flowguard” installed.

**'binary_sensor.thermiq_mqtt_aux1_heating_on'**
This has never been on before. It turned constantly “On” after update 1.3.7-1.3.9. I have it on a Dashboard.

**'binary_sensor.thermiq_mqtt_aux2_heating_on'**
This has never been on before. It turned constantly “On” after update 1.3.7-1.3.9. I have it on a Dashboard.

**'binary_sensor.thermiq_mqtt_hotwaterproduction_on'**
Constantly “On” for me now. Regardless of whether hot water is produced or not.

**'binary_sensor.thermiq_mqtt_shunt1_p'
'binary_sensor.thermiq_mqtt_shunt1_n'
'binary_sensor.thermiq_mqtt_opt_2_installed'
'binary_sensor.thermiq_mqtt_opt_4_installed'
'binary_sensor.thermiq_mqtt_opt_5_installed'
'binary_sensor.thermiq_mqtt_opt_6_installed'**
I don't know what these do, but they are always “On” to.

Is this issue linked to Issue #38 ?

**Comment by ThermIQ** [comment]
Bug introduced in 1.3.6-1.3.9, I'll scrap those releases and will make a new later today

**Comment by ThermIQ** [comment]
Fixed in v1.4.1

**Comment by mbjw77** [comment]
Works. Thank You.
