### ISSUE TITLE
Negative values for passive cooling runtime

### ISSUE THREAD

**Issue by joho01** [ThermIQ/thermiq_mqtt-ha#41]
## Version of the custom_component
v1.3.5

## Configuration
HA: 2022.11.2
HASC: 1.28.3

## Describe the bug
Negative runtime value for "Runtime Passive Cooling" seems masked by 2^16=65536
65536 + (current value) = gives the value presented by my termia

**Comment by ThermIQ** [comment]
Can you check the value in the mqtt message as I'm not sure this is in HA. It could be the ThermIQ-mqtt as well. Which fw version are you on?

**Comment by joho01** [comment]
"app_info": "ThermIQ-mqtt 2.22",
 "d110": -31358

**Comment by ThermIQ** [comment]
Try to update the fw...

**Comment by joho01** [comment]
is already last fw...

**Comment by ThermIQ** [comment]
This is not in the HA integration then but in the ThermIQ fw. Update will be coming soon....

**Comment by ThermIQ** [comment]
Try out the new fw 2.48 where I hope this is resolved

**Comment by ThermIQ** [comment]
Sorry, Not entirely fixed yet

**Comment by ThermIQ** [comment]
Likely solved withfrom v2.50 and up
