### ISSUE TITLE
Missing binary sensors

### ISSUE THREAD

**Issue by markora** [ThermIQ/thermiq_mqtt-ha#43]
Home assistant core version: 2022.11.4
Thermiq: 2.0.5
FW: 1.4?

After the latest update all my thermiq binary sensors got replaced by regular sensors. An example:

sensor.thermiq_mqtt_vp1_boiler_6kw_on

This sensor used to be binary_sensor type previously. It seems that the new sensor is working and updating On and Off values correctly.

Is this the way it should be working from now one or is this a bug? Similar issues for someone else?

**Comment by ThermIQ** [comment]
This is intended for now. The binary sensor has been replace by a normal sensor with 0 and 1 as valid values.

Are there any drawbacks by doing it like this?

Rgds
/&&

**Comment by markora** [comment]
Ok, thanks for the info.

I am surely not an expert not an expert to answer for this. I took the opportunity to ask from discord channel and here is an answer: "(binary sensor) restricts the range of possible values, so don't need to worry about getting random values. `binary_sensor` also has a bunch of standard translations based on `device_class` that `sensor` doesn't have"

Based on this I would say that the latter could be a possible advantage of using binary sensors instead of just sensors.

And the out of scooe values could be a problem but impossible to say without knowing how HW works.

Some more info on developer portal: https://developers.home-assistant.io/docs/core/entity/binary-sensor/

**Comment by jascdk** [comment]
I would also suggest that all sensors that have a state of 1 or 0 should be a binary sensor. IMO it is the most correct :)

**Comment by jascdk** [comment]
> Ok, I'll put it on the backlog but with low priority until base functionality is in place and verified by some more people

@ThermIQ any news on this :)

**Comment by jascdk** [comment]
@ThermIQ any news :)

**Comment by ThermIQ** [comment]
No, feel free to implement and push a change

**Comment by tomrosenback** [comment]
Another point that increases the priority is that groups of sensors are not working as they are expecting numerical values not on/off states.

**Comment by ThermIQ** [comment]
A new beta is available with binary_sensors, @tomrosenback please check it out

**Comment by tomrosenback** [comment]
You are referring to 2.1.1? It seems to work but looking at the code it seems like the BinarySensor entity is missing the is_on property which makes the states be strings instead of booleans.

**Comment by ThermIQ** [comment]
Aha,That makes sense, I thought behaviour was odd, will fix later todayRgds/&&Sent from my Galaxy
-------- Original message --------From: Tom Rosenback ***@***.***> Date: 08/01/2024  10:25  (GMT+01:00) To: ThermIQ/thermiq_mqtt-ha ***@***.***> Cc: ThermIQ ***@***.***>, Mention ***@***.***> Subject: Re: [ThermIQ/thermiq_mqtt-ha] Missing binary sensors (Issue #43) 
You are referring to 2.1.1? It seems to work but looking at the code it seems like the BinarySensor entity is missing the is_on property which makes the states be strings instead of booleans.

**Comment by tomrosenback** [comment]
Tested 2.1.2 now, works perfect! Thank you!

**Comment by ThermIQ** [comment]
Great! Summary of how time was spent:

- 1 Year stalling the task
- 4h to get the development environment running again adding some internal docs on How-to
- 2h Updating the development environment to latest HA
- 15min Coding of feature
- 1h Debug
-- Release and repeat
- 15min Coding and debug

With my new internal How-to I expect that I can shorten the development time for a feature to an hour or so. Still no idea how to address the 1 Year stalling time :-)

/&&

**Comment by jascdk** [comment]
Also running version 2.1.2 here without any issues so far:) great work :)
