### ISSUE TITLE
Calibration of sensors not allowing negative offset in HA

### ISSUE THREAD

**Issue by saaerkk** [ThermIQ/thermiq_mqtt-ha#44]
HA version 2022.12.0
ThermIQ HACS - 2.05

I've noticed that I'm not able in HA to calibrate my sensors with a negative value. The input number does not go negative if I press the - (minus) in the Lovelace Card, positive works and a MQTT is sent. I can manually send a MQTT with a negative value and in ThermIQ 2 web I see that it has taken effect and can confirm that the sensor value is 1 degree lower.
![image](https://user-images.githubusercontent.com/113055615/206841989-c5e2e151-85d0-440b-a430-05e8042006b3.png)
![image](https://user-images.githubusercontent.com/113055615/206842010-c6567893-7ec8-4ac6-9e7b-603b31d43ef7.png)
Pictures from HA and ThermIQ web

**Comment by ThermIQ** [comment]
I've noticed the same and it is fixed in next release

**Comment by ThermIQ** [comment]
Fixed
