### ISSUE TITLE
Entity sensor.thermiq_mqtt_vp1_time should be unix timestamp instead of string

### ISSUE THREAD

**Issue by adriankurtasinski** [ThermIQ/thermiq_mqtt-ha#45]
**Is your feature request related to a problem? Please describe.**
I want to add a timezone to the last reading date/time.
`<div class="hpwidget-val" title="Time"
      style="position:absolute;top:303px;left:20px;width:150px;z-index:3;>  
      <span class="hpwidget-name-span" id="hpwidget-timestamp_d">{{
      states('sensor.thermiq_mqtt_vp1_time_str') }}</span><span
      class="hpwidget-unit-span"></span></span></div>`

**Describe the solution you'd like**
Create a new entity timestamp or replace "sensor.thermiq_mqtt_*_time" with timestamp which is available via mqtt.

**Comment by ThermIQ** [comment]
There is alread such a sensor [sensor.thermiq_mqtt_vp1_time]

**Comment by ThermIQ** [comment]
I will add  [sensor.thermiq_mqtt_vp1_timestamp] as the unix time value in next release

(Something assuming that time started on January 1:st 1970 must of course be included)
