### ISSUE TITLE
Icons hardly visible if HA background set to dark

### ISSUE THREAD

**Issue by erobmil** [ThermIQ/thermiq_mqtt-ha#47]
Just started to use the home assistant thermiq and I noticed that the heatpump icons for cirkulation pump and compressor are visible and black when background is light, but if I select Dark background they turn grayish and are almost not visible. 
Its not much of an issue but still...

**Comment by ThermIQ** [comment]
I'll add that to possible features and close it for now

**Comment by klausdm** [comment]
> Just started to use the home assistant thermiq and I noticed that the heatpump icons for cirkulation pump and compressor are visible and black when background is light, but if I select Dark background they turn grayish and are almost not visible. Its not much of an issue but still...

Fairly easy to fix. Just add `color:black` to the hpwidget style in the lovelace yml, Fx:
`<ha-icon icon="mdi:cog" id="hpwidget-KOMPR" style="_color:black_;position:absolute............`

**Comment by ThermIQ** [comment]
I will close this as it's easily solved like above
