### ISSUE TITLE
Data not showing

### ISSUE THREAD

**Issue by Wellutiainen** [ThermIQ/thermiq_mqtt-ha#48]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/70378591/214837232-563e46ea-25aa-4b97-9408-a2552cae1837.png">

I hope that picture can be seen. 
I have working mqtt alreaydy and have been done hole setup again to hacs intergation and configuration.yalm also to the lovelace by manually.
Still only get -1 or zero value from screen. 
Can some body help if this is not normal or maybe i have done something wrong. 

Thank you for advance

**Comment by ThermIQ** [comment]
Please show how you have configured theintegration in the first step

**Comment by Wellutiainen** [comment]
![image](https://user-images.githubusercontent.com/70378591/214844360-c27dc799-bbf3-4e58-b674-daced168343e.png)
i have tested _vp1 and -bb with and whitout hexformat and debug.

**Comment by Wellutiainen** [comment]
![image](https://user-images.githubusercontent.com/70378591/214850814-bd4de896-15a6-4241-adb9-4d52abda245c.png)

**Comment by ThermIQ** [comment]
I suggest that you clean out everything from configuration.yaml which is no longer used, remove the thermiq integration and restart following the updated install description. You have a mix of v1 and v2 setup that will not work.
