### ISSUE TITLE
TEMP_CELSIUS was used from thermiq_mqtt

### ISSUE THREAD

**Issue by jressel01** [ThermIQ/thermiq_mqtt-ha#52]
after Update to Home Assistant Core 2024.1.0 i get this Warning

TEMP_CELSIUS was used from thermiq_mqtt, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at

**Comment by ThermIQ** [comment]
Will be solved in next release
