### ISSUE TITLE
Adding firmware exposure of the esp32 module via MQTT

### ISSUE THREAD

**Issue by jascdk** [ThermIQ/thermiq_mqtt-ha#53]
**Is your feature request related to a problem? Please describe.**
Fw announcement of hw via MQTT

**Describe the solution you'd like**
I would like to view the fw of the hardware via MQTT so it can be reflected in the integration

Also maybe a way to push the module into updating fw of the hw via MQTT

Would that be possible ? Not need to have but nice to have :) 

all the best

/jacob

**Comment by ThermIQ** [comment]
All that functionality is already available over MQTT but not visible in HA.
The firmware version is already available in the data message in MQTT as app_info, mine currently reads "ThermIQ-room2 2.58"
More info is available by sending MQTT to endpoint /info, that would give detailed app version
Updates of firmware can be done by sending MQTT to endpoint /update

I will add the app_info string as a sensor in next release

**Comment by jascdk** [comment]
Ahhh - great 😎🤘 just updated from 2.54 to 2.58 :) what have Changed ?

**Comment by ThermIQ** [comment]
The outdoor temperature displayed on the oled display will now show negative numbers and not 2-complement. Had some good testing weather lately :-)....

The new HA release with app_info is out

**Comment by jascdk** [comment]
And lastly - a little problem more:) After updating the card now shows this "red dot" - blinking? The sensor shows -1? Am I doing something wrong or is it in the code somewhere? 
![Skærmbillede 2024-01-11 kl  08 01 02](https://github.com/ThermIQ/thermiq_mqtt-ha/assets/35434108/cb2ce64c-dbab-4be8-892d-5c0df7a5652a)

**Comment by nschille** [comment]
> And lastly - a little problem more:) After updating the card now shows this "red dot" - blinking? The communication sensor shows -1? Am I doing something wrong or is it in the code somewhere? ![Skærmbillede 2024-01-11 kl 08 03 25](https://private-user-images.githubusercontent.com/35434108/295819199-b66fac95-2ba2-4700-88ff-4c704682e970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTcwMzgsIm5iZiI6MTcwNDk1NjczOCwicGF0aCI6Ii8zNTQzNDEwOC8yOTU4MTkxOTktYjY2ZmFjOTUtMmJhMi00NzAwLTg4ZmYtNGM3MDQ2ODJlOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjAxMWI3MzliZWIzZjIyNTc3NjI2YjhhOTZjMzY0NzMyOGEyOTAzNzNiZmE0MmE5N2RkMWEyYWI2MmJiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MzzFAxsw3cSl_njclIl5Wzgl0-sH0jXrl6Els0IXTtU)

Same issue here.
Red blinking dot continuously present since update

**Comment by quenthal** [comment]
> > And lastly - a little problem more:) After updating the card now shows this "red dot" - blinking? The communication sensor shows -1? Am I doing something wrong or is it in the code somewhere? 
> 
> Same issue here. Red blinking dot continuously present since update

Not the same red dot as with changing EVU binary switch?

**Comment by ThermIQ** [comment]
New release is availabel to fix that. That is the communication_error dot :-)

**Comment by jascdk** [comment]
Thanks a lot - it fixed it;) Thank you for very quick support!
