### ISSUE TITLE
cached_property

### ISSUE THREAD

**Issue by jascdk** [ThermIQ/thermiq_mqtt-ha#57]
Hi im getting this issue here - not sure what it is ? Is it something that is needed to be fixed?

Logger: homeassistant.backports.functools
Kilde: helpers/deprecation.py:197 
Første forekomst: 13.23.34 (1 forekomster) 
Senest logget: 13.23.34

cached_property was used from thermiq_mqtt, this is a deprecated alias which will be removed in HA Core 2025.5. Use functools.cached_property instead, please report it to the author of the 'thermiq_mqtt' custom integration

**Comment by ThermIQ** [comment]
Fixed in v2.6.7
