### ISSUE TITLE
Name and id is swapped on brine in and brine out sensors

### ISSUE THREAD

**Issue by toreriklarsen** [ThermIQ/thermiq_mqtt-ha#7]
Version 1.1.1

The sensor: sensor.thermiq_brine_out_t has name 'Brine in temp' and the value of brine in 
The sensor: sensor.thermiq_brine_in_t has name 'Brine out temp' and the value of brine out

**Comment by ThermIQ** [comment]
Yes, Fix is comming soon

**Comment by ThermIQ** [comment]
Closed with v1.1.2
